In [1]:
import psycopg2
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
import mitosheet

In [2]:
url_object = URL.create(
    "postgresql+psycopg2",
    username="postgres",
    password="yourpassword",  # plain (unescaped) text
    host="localhost",
    database="crypto_02",
)

In [3]:
engine = create_engine(url_object)

In [4]:
pd.read_sql('BTCUSDT', engine)

                  E         c
0     1670067527877  16945.40
1     1670067528910  16945.86
2     1670067529073  16946.00
3     1670067530944  16946.00
4     1670067531854  16946.50
...             ...       ...
4097  1670334347551  17010.15
4098  1670334348538  17010.20
4099  1670334349565  17009.86
4100  1670334350458  17010.07
4101  1670334351521  17010.02

[4102 rows x 2 columns]

In [5]:
newpd = pd.read_sql('BTCUSDT', engine)

In [ ]:
mitosheet.sheet(newpd)

In [6]:
df = pd.read_sql('BTCUSDT', engine)

In [7]:
(df.c.pct_change() + 1).prod()-1

0.003888961015974468

In [8]:
df

                  E         c
0     1670067527877  16945.40
1     1670067528910  16945.86
2     1670067529073  16946.00
3     1670067530944  16946.00
4     1670067531854  16946.50
...             ...       ...
4119  1670334369384  17011.32
4120  1670334370638  17012.20
4121  1670334371641  17011.58
4122  1670334372591  17011.52
4123  1670334373547  17011.30

[4124 rows x 2 columns]

In [9]:
pd.to_datetime(df.E, unit='ms')

0      2022-12-03 11:38:47.877
1      2022-12-03 11:38:48.910
2      2022-12-03 11:38:49.073
3      2022-12-03 11:38:50.944
4      2022-12-03 11:38:51.854
                 ...
4119   2022-12-06 13:46:09.384
4120   2022-12-06 13:46:10.638
4121   2022-12-06 13:46:11.641
4122   2022-12-06 13:46:12.591
4123   2022-12-06 13:46:13.547
Name: E, Length: 4124, dtype: datetime64[ns]

In [10]:
(df.tail(10).c.pct_change() + 1).prod()-1

1.4696329738494995e-05

In [11]:
dfs = pd.read_sql("""SELECT * FROM information_schema.tables WHERE table_schema = 'public';""", engine)

In [12]:
dfs

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,crypto_02,public,BTCUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
1,crypto_02,public,ETHUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
2,crypto_02,public,BNBUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
3,crypto_02,public,ADAUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
4,crypto_02,public,XRPUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...
331,crypto_02,public,AIONUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
332,crypto_02,public,GHSTUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
333,crypto_02,public,HARDUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
334,crypto_02,public,FXSUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None
335,crypto_02,public,NBTUSDT,BASE TABLE,None,None,None,None,None,YES,NO,None

In [13]:
tables = dfs.table_name.tolist()

In [14]:
tables

['BTCUSDT',
 'ETHUSDT',
 'BNBUSDT',
 'ADAUSDT',
 'XRPUSDT',
 'TRXUSDT',
 'VETUSDT',
 'MITHUSDT',
 'FTMUSDT',
 'WANUSDT',
 'BANDUSDT',
 'BUSDUSDT',
 'XTZUSDT',
 'HBARUSDT',
 'GBPUSDT',
 'EGLDUSDT',
 'ORNUSDT',
 'CTKUSDT',
 'BONDUSDT',
 'RAYUSDT',
 'YGGUSDT',
 'BETAUSDT',
 'JASMYUSDT',
 'BIFIUSDT',
 'LDOUSDT',
 'APTUSDT',
 'PHBUSDT',
 'HOOKUSDT',
 'LTCUSDT',
 'LINKUSDT',
 'ALGOUSDT',
 'DOGEUSDT',
 'RENUSDT',
 'EURUSDT',
 'DOTUSDT',
 'TWTUSDT',
 'SUPERUSDT',
 'ARUSDT',
 'MASKUSDT',
 'FIDAUSDT',
 'LAZIOUSDT',
 'VGXUSDT',
 'PYRUSDT',
 'GLMRUSDT',
 'LOKAUSDT',
 'GMTUSDT',
 'LEVERUSDT',
 'OSMOUSDT',
 'NULSUSDT',
 'MATICUSDT',
 'LRCUSDT',
 'BURGERUSDT',
 'FLOWUSDT',
 'SANTOSUSDT',
 'NKNUSDT',
 'TROYUSDT',
 'BTSUSDT',
 'MBLUSDT',
 'CRVUSDT',
 'WNXMUSDT',
 'SFPUSDT',
 'DEGOUSDT',
 'FARMUSDT',
 'GALUSDT',
 'BELUSDT',
 'CELOUSDT',
 'SHIBUSDT',
 'AGLDUSDT',
 'ANCUSDT',
 'ATOMUSDT',
 'ARPAUSDT',
 'AAVEUSDT',
 'SKLUSDT',
 'VOXELUSDT',
 'STGUSDT',
 'DASHUSDT',
 'RSRUSDT',
 'NEARUSDT',
 'BADGERUSDT',
 'MIRUSDT',
 'NEXOUSDT',
 'GMXUSDT',
 'QTUMUSDT',
 'DOCKUSDT',
 'BLZUSDT',
 'INJUSDT',
 'QIUSDT',
 'RNDRUSDT',
 'BICOUSDT',
 'REIUSDT',
 'RVNUSDT',
 'RIFUSDT',
 'PHAUSDT',
 'BTTCUSDT',
 'ACAUSDT',
 'APEUSDT',
 'EPXUSDT',
 'FETUSDT',
 'CHZUSDT',
 'JSTUSDT',
 'SUSHIUSDT',
 'WINGUSDT',
 'IDEXUSDT',
 'VIDTUSDT',
 'FUNUSDT',
 'RAREUSDT',
 'BNXUSDT',
 'API3USDT',
 'NEBLUSDT',
 'HFTUSDT',
 'WAVESUSDT',
 'MFTUSDT',
 'SOLUSDT',
 'ANTUSDT',
 'DARUSDT',
 'MOVRUSDT',
 'BCHUSDT',
 'ADAUPUSDT',
 'FILUSDT',
 'QUICKUSDT',
 'SCRTUSDT',
 'XLMUSDT',
 'KAVAUSDT',
 'BNTUSDT',
 'LPTUSDT',
 'QNTUSDT',
 'IMXUSDT',
 'BSWUSDT',
 'NEOUSDT',
 'STRAXUSDT',
 'DGBUSDT',
 'YFIIUSDT',
 'AXSUSDT',
 'XNOUSDT',
 'WOOUSDT',
 'VITEUSDT',
 'HIVEUSDT',
 'SANDUSDT',
 'AVAXUSDT',
 'MDXUSDT',
 'OPUSDT',
 'LUNCUSDT',
 'XEMUSDT',
 'XECUSDT',
 'KSMUSDT',
 'ALPACAUSDT',
 'PEOPLEUSDT',
 'COTIUSDT',
 'LITUSDT',
 'RUNEUSDT',
 'PORTOUSDT',
 'SLPUSDT',
 'CVXUSDT',
 'MDTUSDT',
 'LUNAUSDT',
 'CFXUSDT',
 'ICPUSDT',
 'XRPDOWNUSDT',
 'ONEUSDT',
 'BALUSDT',
 'MOBUSDT',
 'ALICEUSDT',
 'SPELLUSDT',
 'ICXUSDT',
 'BEAMUSDT',
 'STMXUSDT',
 'DCRUSDT',
 'UNIUSDT',
 'GTCUSDT',
 'ASTRUSDT',
 'UMAUSDT',
 'DYDXUSDT',
 'ALPINEUSDT',
 'COCOSUSDT',
 'MTLUSDT',
 'DEXEUSDT',
 'WTCUSDT',
 'ASRUSDT',
 'KLAYUSDT',
 'IOTAUSDT',
 'COSUSDT',
 'CLVUSDT',
 'CKBUSDT',
 'BAKEUSDT',
 'ENJUSDT',
 'ROSEUSDT',
 'MCUSDT',
 'TUSDT',
 'ANKRUSDT',
 'RLCUSDT',
 'XRPUPUSDT',
 'DENTUSDT',
 'IOTXUSDT',
 'OXTUSDT',
 'KDAUSDT',
 'KEYUSDT',
 'XVGUSDT',
 'SYSUSDT',
 'MANAUSDT',
 'UTKUSDT',
 'THETAUSDT',
 'LINKUPUSDT',
 'GRTUSDT',
 'RADUSDT',
 'ETCUSDT',
 'HOTUSDT',
 'YFIUSDT',
 'GALAUSDT',
 'ADXUSDT',
 'MINAUSDT',
 'TOMOUSDT',
 'JOEUSDT',
 'BATUSDT',
 'CAKEUSDT',
 'STXUSDT',
 'TLMUSDT',
 'ZECUSDT',
 'OCEANUSDT',
 'SUNUSDT',
 'CVPUSDT',
 'MKRUSDT',
 'AUDUSDT',
 'LINAUSDT',
 'C98USDT',
 'ONGUSDT',
 'WRXUSDT',
 'KNCUSDT',
 'LINKDOWNUSDT',
 'TFUELUSDT',
 'ZENUSDT',
 'KMDUSDT',
 'ERNUSDT',
 'ETHUPUSDT',
 'OMUSDT',
 'TRBUSDT',
 'TORNUSDT',
 'UNFIUSDT',
 'COMPUSDT',
 'EOSUSDT',
 'ZILUSDT',
 'CITYUSDT',
 'POLYXUSDT',
 '1INCHUSDT',
 'WAXPUSDT',
 'ALPHAUSDT',
 'HIGHUSDT',
 'VTHOUSDT',
 'AVAUSDT',
 'ONTUSDT',
 'FLUXUSDT',
 'CTSIUSDT',
 'TRUUSDT',
 'ETHDOWNUSDT',
 'AUDIOUSDT',
 'ATAUSDT',
 'STORJUSDT',
 'FISUSDT',
 'DUSKUSDT',
 'ACHUSDT',
 'REPUSDT',
 'CTXCUSDT',
 'WINUSDT',
 'PNTUSDT',
 'REQUSDT',
 'XMRUSDT',
 'FIOUSDT',
 'MBOXUSDT',
 'FORTHUSDT',
 'AUCTIONUSDT',
 'AKROUSDT',
 'OMGUSDT',
 'ARDRUSDT',
 'SNXUSDT',
 'PONDUSDT',
 'PERPUSDT',
 'TKOUSDT',
 'REEFUSDT',
 'BNBDOWNUSDT',
 'ELFUSDT',
 'ZRXUSDT',
 'OGNUSDT',
 'SXPUSDT',
 'IRISUSDT',
 'XVSUSDT',
 'CHESSUSDT',
 'ENSUSDT',
 'PAXGUSDT',
 'DATAUSDT',
 'BTCUPUSDT',
 'BTCDOWNUSDT',
 'TVKUSDT',
 'AMPUSDT',
 'LTOUSDT',
 'ADADOWNUSDT',
 'MULTIUSDT',
 'DODOUSDT',
 'SCUSDT',
 'DIAUSDT',
 'STPTUSDT',
 'CHRUSDT',
 'PLAUSDT',
 'CELRUSDT',
 'CVCUSDT',
 'BARUSDT',
 'KP3RUSDT',
 'ATMUSDT',
 'JUVUSDT',
 'FLMUSDT',
 'MLNUSDT',
 'AUTOUSDT',
 'DREPUSDT',
 'ACMUSDT',
 'NMRUSDT',
 'GNOUSDT',
 'DFUSDT',
 'PUNDIXUSDT',
 'ALCXUSDT',
 'STEEMUSDT',
 'OOKIUSDT',
 'FIROUSDT',
 'PERLUSDT',
 'OGUSDT',
 'PSGUSDT',
 'POLSUSDT',
 'ILVUSDT',
 'POWRUSDT',
 'LSKUSDT',
 'FRONTUSDT',
 'IOSTUSDT',
 'BNBUPUSDT',
 'FORUSDT',
 'AIONUSDT',
 'GHSTUSDT',
 'HARDUSDT',
 'FXSUSDT',
 'NBTUSDT']

In [15]:
file1 = open("data.txt", "a")
for table in tables:
    #write tables to external file: data.txt
    file1.write(table)
    file1.write('\n')
    #table.lower()
    #print(pd.read_sql_table(table, engine))
    #df__ = pd.read_sql_table(table, engine)
    #df__ = pd.read_sql(table, engine)
    #print(df__)
    #ret_ = (df__.c.pct_change() + 1).prod()-1
    #returns.append(ret_)
file1.close()

In [16]:
returns = []

for table in tables:
    df__ = pd.read_sql_table(table, engine)
    ret_ = (df__.c.pct_change() + 1).prod()-1
    returns.append(ret_)

In [18]:
pd.Series(returns, index=tables).nlargest(20)

TKOUSDT      0.705085
YFIIUSDT     0.465484
NMRUSDT      0.375328
AXSUSDT      0.324168
AGLDUSDT     0.197080
CTSIUSDT     0.176106
FETUSDT      0.157143
UMAUSDT      0.123312
LITUSDT      0.109741
DODOUSDT     0.101874
FXSUSDT      0.098641
UTKUSDT      0.097837
SNXUSDT      0.090389
ANTUSDT      0.081389
ILVUSDT      0.078947
GALAUSDT     0.077412
FORTHUSDT    0.072508
YFIUSDT      0.069681
CTXCUSDT     0.068660
CRVUSDT      0.066563
dtype: float64